### PR TITLE
WSSRV007 Test - Windows Firewall startup mode check

### PR DESCRIPTION
**Pull request by damianscoles**
This test will check the Windows Firewall startup mode.  To pass the service must be set to Automatic.  Any other setting will cause the test
to fail.

---

This change is [Reviewable](https://reviewable.io/reviews/exchangeanalyzer/exchangeanalyzer/163)

### CODE REVIEW

**Comment by cunninghamp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Data/Tests.xml, line 164 \[r1\]](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/163#-KHS03JpRrznb8S26_N1:-KHS03Jq8Rf0kwOgC9OM:1133877797) ([raw file](https://github.com/exchangeanalyzer/exchangeanalyzer/blob/ba0234e97142b1766eca9c0aee11204362b597ed/Data/Tests.xml#L164)):*
> ```XML
> 		<IfInfoComments></IfInfoComments>
> 		<IfPassedComments>The Windows Firewall service is set to Automatic startup.</IfPassedComments>
> 		<IfWarningComments>A CIM or WMI connection to the server could not be made.</IfWarningComments>		
> ```

These comments should be written in the context of the entire report. It could be "the server" or multiple servers.

---

*[Tests/WSSRV007.ps1, line 59 \[r1\]](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/163#-KHS0w_jHiclAC_6_eGW:-KHS0w_jHiclAC_6_eGX:710806437) ([raw file](https://github.com/exchangeanalyzer/exchangeanalyzer/blob/ba0234e97142b1766eca9c0aee11204362b597ed/Tests/WSSRV007.ps1#L59)):*
> ```PowerShell
>             # Script failed to connect to the server and is added to the warning list
>             write-verbose "There was an issue connecting to the $ServerName server. "
>             $WarningList += $($ServerName)
> ```

Consider adding a comment to these warnings so it appears in the report, e.g

```
$WarningList += "$($ServerName) - Unable to connect to server"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/163)*

**Comment by bdesmond** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/WSSRV007.ps1, line 27 \[r1\]](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/163#-KHSvVGjHQKUMKP6dlDi:-KHSvVGjHQKUMKP6dlDj:-1527202802) ([raw file](https://github.com/exchangeanalyzer/exchangeanalyzer/blob/ba0234e97142b1766eca9c0aee11204362b597ed/Tests/WSSRV007.ps1#L27)):*
> ```PowerShell
> 
>         try {
>             $FirewallState = (Get-CIMInstance -Class win32_service -filter "name = 'mpssvc'" -ComputerName $ServerName -erroraction STOP).startmode
> ```

Why aren't we using the new WMI helpers? If we need one for CIM, let's duplicate and put it in place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/163)*

**Comment by cunninghamp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/WSSRV007.ps1, line 27 \[r1\]](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/163#-KHSvVGjHQKUMKP6dlDi:-KHSzlbMO2fifJC5IT2T:1210716950) ([raw file](https://github.com/exchangeanalyzer/exchangeanalyzer/blob/ba0234e97142b1766eca9c0aee11204362b597ed/Tests/WSSRV007.ps1#L27)):*
<details><summary><i>Previously, bdesmond (Brian Desmond) wrote…</i></summary>
> Why aren't we using the new WMI helpers? If we need one for CIM, let's duplicate and put it in place.
> </details>
Doco? A wiki page with a handful of examples would be sufficient. Eg. how to query a reg key, how to query a service's properties, how to query some other WMI class like Win32_OperatingSystem. We've got a few WMI/CIM/reg tests floating around now and the number will keep growing, so we should jump on this now and set the standard for future tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/163)*

**Comment by swngdnz** [comment]
I wrote a generic CIM tester, but I'm still fighting the tooling. I can't figure git out.

Yes, yes, I realize I'm an idiot. 

But I thought I posted the function to the general distribution.

**Comment by cunninghamp** [comment]
Probably time I wrote a short tut then.

**Comment by cunninghamp** [comment]
Closing stale PRs. Resubmit after testing if still valid.

**Pull request closed without merging**
