### PR TITLE
NET001

### PR DESCRIPTION
**Pull request by damianscoles**
This function checks to see if the Exchange Server NIC power management is enabled or disabled.

### CODE REVIEW

**Comment by swngdnz** [comment]
this test isn't accurate. there are a number of other settings that come into play with PnPSettings. For just a few examples, see:

http://www.ephingadmin.com/a-configmgr-admins-guide-to-wol-magic-part-two/
http://deploywindows.info/2013/02/19/power-management-for-devices/
https://social.technet.microsoft.com/Forums/windowsserver/en-US/eb42064a-8ee2-4a63-867b-4ab416684c8e/how-do-i-disable-allow-the-computer-to-turn-off-this-device-to-save-power-for-nic-power?forum=windowsserver2008r2networking
http://blog.compower.org/2012/09/18/windows-7-unattended-disabling-the-allow-the-computer-to-turn-off-this-device-to-save-power/
http://stackoverflow.com/questions/21098876/network-card-power-management-settings
https://support.microsoft.com/en-us/kb/837058

**Comment by damianscoles** [comment]
The test is accurate.  Please refer to this KB article - https://support.microsoft.com/en-us/kb/2740020.  As per the MS article, if we need to disable PowerManagement for a NIC:
"How to use Registry Editor to disable network adapter power management on a single computer"
2. Locate and then click the following registry subkey: 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002bE10318}\DeviceNumber
NoteDeviceNumber is the network adapter number. If a single network adapter is installed on the computer, the DeviceNumber is 0001.
3. Click PnPCapabilities.
4. On the Edit menu, click Modify.
In the Value data box, type 24, and then click OK.

**Comment by swngdnz** [comment]
So, to be more specific, referring to that same article... read the "Additional Information". Minimally you also need to compare $Pnp to 280 (0x118), not just 24 (0x18). I also have this written as a Config Manager script for Server 2008/2008R2 where the value I set is 56 (0x38), so I know that at some point that value was documented.

The title is for "High Performance" whereas the results are for "Power Management Disabled".

If you want to check for high performance, the query is "Get-CimInstance -ComputerName $name -Classname Win32_PowerPlan -NameSpace root\cimv2\power" and the item you are looking for has IsActive -eq $true -and $ElementName -eq 'High Performance'.

Also, does this only update physical NICs? I'm not familiar with the WMI query you use and I can't check right now.

**Comment by damianscoles** [comment]
I updated the title and will make sure the test is the same,  The test will work with virtual NICs (verified in a few labs already).  This may get re-written in CIM which was suggested privately.  As for the values, the test is simple.  I want to make sure that we disable the server from managed the power on the NIC.  The suggested change came from this article - http://blogs.technet.com/b/exchange/archive/2013/10/22/do-you-have-a-sleepy-nic.aspx.  The best way to disable it is to set the value to 0x24.

Hope that explains it a bit better.   Thanks for the feedback.

**Comment by cunninghamp** [comment]
Closing stale PRs. Resubmit after testing if still valid.

**Pull request closed without merging**
