### PR TITLE
AD003

### PR DESCRIPTION
**Pull request by damianscoles**
Adds test - Some DCs aren't GCs for issue #140

---

This change is [Reviewable](https://reviewable.io/reviews/exchangeanalyzer/exchangeanalyzer/164)

### CODE REVIEW

**Comment by bdesmond** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Data/Tests.xml, line 143 \[r1\]](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/164#-KHSv149ud4VPVsRaGfB:-KHSv149ud4VPVsRaGfC:1412617484) ([raw file](https://github.com/exchangeanalyzer/exchangeanalyzer/blob/77bb55f4b3e2f21669fac07d61b1e6ca92195b94/Data/Tests.xml#L143)):*
> ```XML
> 		<IfPassedComments>All Active Directory Domain Controllers are Global Catalog Servers.</IfPassedComments>
> 		<IfWarningComments></IfWarningComments>
> 		<IfFailedComments>One or more Active Directory Domain Controllers are not Global Catalog Servers.</IfFailedComments>
> ```

This isn't necessarily a failure state. There are many good reasons why a customer might have this. This should be informational.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/164)*

**Comment by damianscoles** [comment]
True enough.  I just changed the designation in the script.

**Comment by bdesmond** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/164)*

**Comment by bdesmond** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Data/Tests.xml, line 143 \[r1\]](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/164#-KHSv149ud4VPVsRaGfB:-KI3RCCzevhQTTcHveWc:5173665) ([raw file](https://github.com/exchangeanalyzer/exchangeanalyzer/blob/77bb55f4b3e2f21669fac07d61b1e6ca92195b94/Data/Tests.xml#L143)):*
<details><summary><i>Previously, bdesmond (Brian Desmond) wrote…</i></summary>
> This isn't necessarily a failure state. There are many good reasons why a customer might have this. This should be informational.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/exchangeanalyzer/exchangeanalyzer/164)*

**Comment by cunninghamp** [comment]
Closing stale PRs. Resubmit after testing if still valid.

**Pull request closed without merging**
