### PR TITLE
CAS004

### PR DESCRIPTION
**Pull request by damianscoles**
Checks to see if the RC4 cipher is enabled (should be disabled)

### CODE REVIEW

**Comment by cunninghamp** [comment]
This looks nearly identical to CAS003

**Comment by damianscoles** [comment]
Wrong test got copied up.  Will fix this now.

**Comment by damianscoles** [comment]
Code is fixed now.

**Comment by cunninghamp** [comment]
Line 73 has a typo:

```
$succes = $false
```

Also, emailed you some notes from CAS003 that will be relevant to this test as well, since they share similar code and logic.

**Comment by damianscoles** [comment]
Fixed the typo at line #73.

**Comment by cunninghamp** [comment]
Closing stale PRs. Resubmit after testing if still valid.

**Pull request closed without merging**
